package:
  name: cgmlstfinder
  version: 1.1.5

source:
  url: https://bitbucket.org/genomicepidemiology/cgMLSTFinder/get/1.1.5.tar.gz

build:
  number: 0
  noarch: generic

requirements:
  host:
    - python>=3.5
    - kma
    - wget
  run:
    - python>=3.5
    - kma
    - biopython
    - ete3
    - tabulate
    - cgecore
    - blast
test:
  commands:
    - cgMLST.py -h | grep cgMLST.py >/dev/null

about:
  home: https://bitbucket.org/genomicepidemiology/cgMLSTFinder
  license: Apache-2.0
  summary: "Core genome Multi-Locus Sequence Typing cgMLSTFinder runs KMA [1] against a chosen core genome MLST (cgMLST) database and outputs the detected alleles in a matrix file."